FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN install_packages wget jq

COPY . /

COPY start.sh /usr/src/

ADD https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-aarch64_bin.tar.gz /opt/

RUN tar -zxf /opt/openjdk-16.0.1_linux-aarch64_bin.tar.gz -C /opt/

RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
