FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-openjdk:latest-buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN install_packages wget

COPY . /

COPY start.sh /usr/src/

RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
